services:
  mongodb_db:
    image: mongo:latest
    container_name: mongo_local
    environment:
      MONGO_INITDB_ROOT_USERNAME: nobzo_user
      MONGO_INITDB_ROOT_PASSWORD: Mogdb}D0c. # <--- CHANGE THIS
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    restart: always

volumes:
  mongodb_data:
